### ISSUE TITLE
revise some functions

### ISSUE THREAD

**Issue by tyhsu** [dream040102/Ewn#4]
## The order of the game:

(1) roll the dice
-> (2) **_player chooses and return a movement(chess, direction)**_
-> (3) update the board(have a move), chsNum, playerA/playerB, is game end? who win?
-> (4) print the board
-> (5) switch
-> (1) roll the dice (loop)

ps. (2) is what's done in playerPlay
## Tasks:
- [x] have a new class(structure?) for playerPlay() to return chess and direction?
- [x] updatePlayer => receive a movement and return who wins
- [x] modify playerPlay()
#### add at 10/22
- [x] isLegal(int x, int y)  -> isLegal(chess chs, int cmd, int direction)
- [x] Random
- [x] Mapping evaluate function
- [x]  Minimax

**Comment by tyhsu** [comment]
**抱歉我覺得我好像有點錯亂，上面那個ps請先忽略好了，我好像有點不知道他應該是哪個function＠＠
- 上面一行大概是一個function
- 想要把code改成這樣的寫法，是因為之後我們大概是會跑別人寫的game，而「下 一步棋」回傳一個0, 1, 2去表示「遊戲繼續？誰贏」這件事有點沒有human sense(?)，不管是player還是ai都很奇怪(雖然player可以不管)；他應該是讀了board之後，做評斷決定，然後回傳「棋子+移動方向」
- updatePlayer這東西應該是收到上面那個「棋子+移動方向」之後，去對board做改變並更新其他東西。因為是game裡面的東西我們可以自己寫，所以可以跟isGameEnd直接做合併，一樣回傳0, 1, 2
- 有些東西也許可以「參考」Blokus，雖然可能也沒寫得很好XD

**Comment by lichin-lin** [comment]
Mapping function 需要討論來自棋盤或是player

**Comment by tyhsu** [comment]
### The pseudo code of minimax

```
function minimax(curBoard, height, maximizingPlayer)
    if height==0    //node is a terminal node
        return the feature value of node    //heuristic value

    if maximizingPlayer
        bestValue := -∞
        // according to maximizingPlayer, know which player to play
        for each possible move chs, dirct   //each child of node
            nxtBoard := curBoard    //copy
            nxtBoard.move(chs, dirct)
            val := minimax(nxtBoard, height-1, FALSE)
            bestValue := max(bestValue, val);
        return bestValue
    else
        bestValue := +∞
        for each possible move chs, dirct
            nxtBoard := curBoard    //copy
            nxtBoard.move(chs, dirct)
            val := minimax(nxtBoard, height-1, TRUE)
            bestValue := min(bestValue, val);
        return bestValue

(* Initial call for maximizing player *)
minimax(origin, height, TRUE)
```
